version: '3.7'
services:
  postgresql:
    image: postgres:12-alpine
    ports:
      - '3306:3306'
    volumes:
      - ./data:/var/lib/postgres
    environment:
      - POSTGRES_DB=base
      - POSTGRES_USER=asd
      - POSTGRES_PASSWORD=9mREsvXDs9Gk89Ef